version: "3.8"

services:
  crimea-cities:
    image: ipoglif/crimea-cities:latest
    container_name: crimea-cities
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      - DB_HOST=mysql
      - DB_NAME=crimea_cities
      - DB_DIALECT=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASS=aeG8oSN2
      - CITIES_SERVICE_HOST=crimea-cities
    ports:
      - 3006:3006
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - crimea-network