version: "3.8"

services:
  crimea-cities:
    image: ipoglif/crimea-cities:latest
    container_name: crimea-cities
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=crimea_cities
      - SERVICE_HOST=crimea-cities
      - SERVICE_PORT=3006
    ports:
      - 3006:3006
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - crimea-network