version: "3.8"

services:
  crimea-geteway:
    image: crimea-geteway:latest
    container_name: crimea-geteway
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      - CITIES_SERVICE_HOST=crimea-cities
    ports:
      - 3000:3000
    networks:
      - crimea-network